/* eslint-disable camelcase */
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const url = 'https://api.spacexdata.com/v3/rockets';

const rocketsAsync = createAsyncThunk(
  'rockets/fetchRockets',
  async () => {
    const response = await fetch(url);
    const fetchedData = await response.json();
    return fetchedData;
  },
);

const rocketsSlice = createSlice({
  name: 'rockets',
  initialState: { status: '', value: [] },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(rocketsAsync.pending, (state) => {
        const newState = { ...state };
        newState.status = 'loading';
        return newState;
      })
      .addCase(rocketsAsync.fulfilled, (state, action) => {
        const newState = { ...state };
        newState.status = 'idle';
        newState.value = action.payload;
        return newState;
      });
  },
});

export default rocketsSlice.reducer;

export { rocketsAsync };
